# KickPi-OS Init Script starter

clear
toilet "KickPi-OS" --metal
echo "KickPI-OS ROM Operating System and Libraries" 
echo "Version V1.5 2020-2021 KickPi-OS "
echo "No Rights Reserved.  "
echo ""
cp -rf /opt/KickPi-OS/scripts/.bashrc /home/$USER/.bashrc

startx

